name: dragablegridview_flutter
description: A dragable gridview,Long-pressed triggers draggable state,GridView reordering after release your finger
version: 0.1.6
author: baoolong <baoolong1987@gmail.com>
homepage: https://github.com/baoolong/DragableGridview

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

